### ISSUE TITLE
Fix xclip installation in CI

### ISSUE THREAD

**Issue by SebastianM-C** [SebastianM-C/PkgCite.jl#11]
In order to test the clipboard integration `xclip` can be installed, but it requires an X server.
We should also run tests on other platforms (Windows and Mac-OS).

**Comment by hyrodium** [comment]
Hi! I'm a developer of [ImageClipboard.jl](https://github.com/hyrodium/ImageClipboard.jl) which uses `xclip`. There was the same issue, and it was solved with `xvfb-run`.

[The `CI.yml` in the repo](https://github.com/hyrodium/ImageClipboard.jl/blob/master/.github/workflows/CI.yml) might be helpful.
