### ISSUE TITLE
Option to only get citations of packages in Project.toml and not in Manifest.toml

### ISSUE THREAD

**Issue by Datseris** [SebastianM-C/PkgCite.jl#18]
I just used `get_tool_citation()` which gave me citation for 50 more names that I've ever seen in my life. But that's not really how citing works; you cite things you used directly and you have seen directly. If e.g., you cite a scientific paper from the 80s, you don't also cite all the papers that paper cites.

An option of only collecting the packages explicitly in the Project.toml file would resolve this.

**Comment by Datseris** [comment]
E.g., even though I do not use Measurements.jl in my work, aparrently some package has some deep dependency on Measurements.jl and its included in my "citation clipboard".

**Comment by SebastianM-C** [comment]
You can use `only direct=true` in this case (see https://sebastianm-c.github.io/PkgCite.jl/stable/#PkgCite.get_citations). Does that solve the issue?

**Comment by Datseris** [comment]
Oh, sorry I have not realized there is an online hosted docs, I was reading the README. Yes this is a good solution, but would be also nice to have in the `get_tool_citation() ` which copies this convenient string into clipboard.

**Comment by Datseris** [comment]
Oh that's already possible. Thanks!

**Comment by Datseris** [comment]
(p.s.: I think `only_direct = true` should be the default argument. It doesn't seem natural to reference any package in the Manifest)

**Comment by SebastianM-C** [comment]
There was a discussion about this on slack and there were people arguing for both sides, so that's why I left it like this.

The `only_direct` option should also work with `get_tool_citation`, but I think there is an omission in the docs. Thanks for bringing it to my attention.
